version: 2
jobs:
  build:
    working_directory: ~/symfony-01
    docker:
        - image: circleci/php:7.2.4-apache-stretch-node-browsers
          environment:
             APP_ENV: test
             DATABASE_URL: mysql://root:root@127.0.0.1/symfony-01
             MAILER_FROM: null://localhost
        - image: circleci/mysql:5.7
          environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: symfony-01
    steps:
        - checkout
        - run:
            name: Install apt
            command: sudo apt-get install -y zlib1g-dev
        - run:
            name: Install PHP MySQL
            command: sudo docker-php-ext-install pdo_mysql zip
        - run:
            name: Wait for composer
            command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
        - run:
             name: Composer
             command: sudo composer self-update
        - run:
              name: Composer install
              command: composer install -n --prefer-dist
        - run:
              name: Run migrations
              command: php bin/console  doctrine:migrations:migrate --env=test --no-interaction
        - run:
              name: Run tests
              command: ./bin/phpunit